name: ams_try2
description: "Frontend for AMS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fpdart: ^1.2.0
  http: ^1.6.0
  flutter_secure_storage: ^8.0.0
  flutter_riverpod: ^2.6.0
  flutter_dotenv:
  image_picker: ^1.0.7
  permission_handler: ^11.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
