name: ams_try2
description: "Frontend for AMS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fpdart: ^1.2.0
  http: ^1.6.0
  flutter_secure_storage: ^8.0.0
  flutter_riverpod: ^2.6.0
  flutter_dotenv:
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  pdf: ^3.10.6
  printing: ^5.11.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
